// Tanggung jawab: penulis file VCD (Value Change Dump) dari sampel nilai sinyal.
use std::fmt::Write as _;
use std::io;
use std::path::Path;

/// Index sinyal yang terdaftar pada writer.
pub type SignalId = usize;

/// Penulis VCD: terima header lalu deretan sampel (waktu, nilai) dan tulis file.
pub struct VcdWriter {
    names_widths: Vec<(String, u32)>,
    codes: Vec<String>,
    last: Vec<String>,
    buf: String,
    timescale: String,
    emitted_header: bool,
}

impl VcdWriter {
    /// Buat writer baru dengan timescale (mis. `"1ns"`).
    pub fn new(timescale: impl Into<String>) -> Self {
        Self {
            names_widths: Vec::new(),
            codes: Vec::new(),
            last: Vec::new(),
            buf: String::new(),
            timescale: timescale.into(),
            emitted_header: false,
        }
    }

    /// Daftarkan satu sinyal berlebar `width`; kembalikan id sebagai referensi sampel.
    pub fn add_signal(&mut self, name: impl Into<String>, width: u32) -> SignalId {
        let id = self.names_widths.len();
        self.names_widths.push((name.into(), width));
        self.codes.push(code_for(id));
        id
    }

    /// Tulis header VCD: date, version, timescale, scope, dan deklarasi semua sinyal.
    pub fn begin(&mut self) {
        if self.emitted_header {
            return;
        }
        let _ = writeln!(self.buf, "$date");
        let _ = writeln!(self.buf, "Generated by sv-rust");
        let _ = writeln!(self.buf, "$end");
        let _ = writeln!(self.buf, "$version");
        let _ = writeln!(self.buf, "svrust {}", env!("CARGO_PKG_VERSION"));
        let _ = writeln!(self.buf, "$end");
        let _ = writeln!(self.buf, "$timescale");
        let _ = writeln!(self.buf, "{}", self.timescale);
        let _ = writeln!(self.buf, "$end");
        let _ = writeln!(self.buf, "$scope");
        let _ = writeln!(self.buf, "module");
        let _ = writeln!(self.buf, "top");
        let _ = writeln!(self.buf, "$end");
        for (i, (name, width)) in self.names_widths.iter().enumerate() {
            let _ = writeln!(
                self.buf,
                "$var wire {} {} {} $end",
                width, self.codes[i], name
            );
        }
        let _ = writeln!(self.buf, "$upscope");
        let _ = writeln!(self.buf, "$end");
        let _ = writeln!(self.buf, "$enddefinitions");
        let _ = writeln!(self.buf, "$end");
        self.last.resize(self.names_widths.len(), String::new());
        self.emitted_header = true;
    }

    /// Tulis blok `$dumpvars` berisi nilai awal seluruh sinyal.
    pub fn initial(&mut self, values: &[(SignalId, &str)]) {
        self.begin();
        let _ = writeln!(self.buf, "$dumpvars");
        for &(id, value) in values {
            self.write_change(id, value);
            self.last[id] = value.to_string();
        }
        let _ = writeln!(self.buf, "$end");
    }

    /// Tulis `#<waktu>` lalu nilai yang berubah sejak sampel sebelumnya.
    pub fn advance(&mut self, time: u64, values: &[(SignalId, &str)]) {
        self.begin();
        let mut changed = Vec::new();
        for &(id, value) in values {
            let changed_now = match self.last.get(id) {
                Some(prev) => prev != value,
                None => true,
            };
            if changed_now {
                changed.push((id, value));
            }
        }
        if changed.is_empty() {
            return;
        }
        let _ = writeln!(self.buf, "#{}", time);
        for (id, value) in changed {
            self.write_change(id, value);
            self.last[id] = value.to_string();
        }
    }

    /// Selesaikan penulisan; memastikan header sudah hadir.
    pub fn finish(&mut self) {
        self.begin();
    }

    /// Tulis seluruh VCD ke file.
    pub fn write_to_file(&mut self, path: impl AsRef<Path>) -> io::Result<()> {
        self.finish();
        std::fs::write(path, self.buf.as_bytes())
    }

    /// Salin isi VCD (untuk pengujian dan verifikasi).
    pub fn vcd_text(&self) -> &str {
        &self.buf
    }

    /// Tulis satu baris perubahan nilai dengan format sesuai lebar sinyal.
    fn write_change(&mut self, id: SignalId, value: &str) {
        let (_, width) = self.names_widths[id];
        let code = &self.codes[id];
        if width == 1 {
            // Skalar: nilai tunggal diikuti kode identifier.
            let ch = value.chars().next().unwrap_or('x');
            let _ = writeln!(self.buf, "{}{}", ch, code);
        } else {
            // Vektor: b<nilai biner><identifier>.
            let _ = writeln!(self.buf, "b{}{}", value, code);
        }
    }
}

/// Encode urutan sinyal ke kode identifier VCD (base-94, char 33..=126).
fn code_for(index: usize) -> String {
    let mut n = index;
    let mut out = String::new();
    loop {
        out.push((33 + (n % 94) as u32) as u8 as char);
        n /= 94;
        if n == 0 {
            break;
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn header_declares_timescale_scope_and_vars() {
        let mut w = VcdWriter::new("1ns");
        w.add_signal("a", 4);
        w.add_signal("clk", 1);
        w.begin();
        let txt = w.vcd_text();
        assert!(txt.contains("$timescale\n1ns\n$end"));
        assert!(txt.contains("$var wire 4 ! a $end"));
        assert!(txt.contains("$var wire 1 \" clk $end"));
        assert!(txt.contains("$scope\nmodule\ntop\n$end"));
        assert!(txt.contains("$enddefinitions"));
    }

    #[test]
    fn initial_writes_dumpvars_vector_value() {
        let mut w = VcdWriter::new("1ps");
        let a = w.add_signal("a", 4);
        w.initial(&[(a, "0101")]);
        let txt = w.vcd_text();
        assert!(txt.contains("$dumpvars"));
        assert!(txt.contains("b0101!"));
    }

    #[test]
    fn advance_only_writes_changed_signals() {
        let mut w = VcdWriter::new("1ns");
        let a = w.add_signal("a", 4);
        let b = w.add_signal("b", 1);
        w.initial(&[(a, "0000"), (b, "0")]);
        w.advance(10, &[(a, "0001"), (b, "0")]);
        let txt = w.vcd_text();
        assert!(txt.contains("#10\nb0001!\n"));
        assert!(!txt.contains("#10\n0\""));
    }

    #[test]
    fn scalar_uses_direct_value() {
        let mut w = VcdWriter::new("1ns");
        let c = w.add_signal("c", 1);
        w.initial(&[(c, "1")]);
        assert!(w.vcd_text().contains("1!"));
    }

    #[test]
    fn id_codes_increment() {
        let codes: Vec<String> = (0..4).map(code_for).collect();
        assert_ne!(codes[0], codes[1]);
        assert_ne!(codes[1], codes[2]);
    }
}
