// Tanggung jawab: generate struct Rust untuk satu design module.
use crate::indent::Indent;
use crate::stmt_gen::write_statements;
use sv_ir::expr::Expr;
use sv_ir::process::{ProcessKind, Statement};
use sv_ir::Design;

const HEADER: &str = "// Generated by sv-codegen-rust. Jangan edit manual.\n";

/// Generate satu file Rust untuk design.
pub fn generate_module(design: &Design) -> String {
    let mut out = String::new();
    let indent = Indent::new();
    let struct_name = to_struct_name(&design.name);
    let max_width = max_width(design);

    out.push_str(HEADER);
    out.push_str(imports());
    out.push_str(&format!(
        "/// Lebar maksimum sinyal pada design `{}`.\n",
        design.name
    ));
    out.push_str(&format!("pub const MAX_WIDTH: usize = {};\n\n", max_width));
    // Field `sensitivity` dipakai scheduler (milestone event queue) dan
    // `initial_pc` hanya dibaca oleh varian driver bertahap; keduanya boleh
    // tidak terbaca pada driver biasa.
    out.push_str("#[allow(dead_code)]\n");
    out.push_str(&format!("pub struct {0} {{\n", struct_name));
    let field_indent = indent.child();
    field_indent.push(&mut out);
    out.push_str("signals: Vec<SignalCell<MAX_WIDTH>>,\n");
    field_indent.push(&mut out);
    out.push_str("pending: Vec<PendingWrite<MAX_WIDTH>>,\n");
    field_indent.push(&mut out);
    out.push_str("sensitivity: Vec<Vec<usize>>,\n");
    // Flag `$finish` dibutuhkan bila ada blok `initial` ATAU ada proses
    // sekuensial/combinational yang memanggil `$finish`. Gate hanya pada
    // `has_initial` membuat `$finish` di dalam `always_ff` pada design tanpa
    // `initial` tidak punya field untuk ditugaskan.
    let perlu_finish = has_initial(design) || crate::system_task_gen::has_finish(design);
    if perlu_finish {
        field_indent.push(&mut out);
        out.push_str("finished: bool,\n");
    }
    if has_initial(design) {
        // LRM §15.2: tiap proses `initial` punya penunjuk segmen sendiri.
        // Pointer hanya maju setelah segmen selesai, sehingga segmen yang
        // menunggu `@(posedge clk)` boleh dicoba lagi pada langkah berikutnya.
        field_indent.push(&mut out);
        out.push_str("initial_pc: Vec<usize>,\n");
    }
    // Nilai sinyal yang diawasi event control pada langkah sebelumnya,
    // dipakai untuk mengenali posedge/negedge (LRM §9.7).
    if perlu_edge_prev(design) {
        field_indent.push(&mut out);
        out.push_str("edge_prev: Vec<u64>,\n");
    }
    // Waktu simulasi hanya perlu ada bila ada `#delay` atau `$time`.
    if crate::time_scan::has_time(design) {
        field_indent.push(&mut out);
        out.push_str("time_now: SimTime,\n");
    }
    // State `$monitor` hanya perlu ada bila design memakainya.
    if crate::system_task_gen::uses_monitor_flag(design) {
        field_indent.push(&mut out);
        out.push_str("monitor_fmt: &'static str,\n");
        field_indent.push(&mut out);
        out.push_str("monitor_args: Vec<sv_runtime::FormatArg<MAX_WIDTH>>,\n");
        field_indent.push(&mut out);
        out.push_str("monitor_active: bool,\n");
        // LRM §20.2: `$monitor if (kondisi)` menyimpan hasil syarat saat ini.
        if crate::system_task_gen::monitor_condition(design).is_some() {
            field_indent.push(&mut out);
            out.push_str("monitor_cond: bool,\n");
        }
    }
    // LRM §20.3: `$strobe` perlu antrean panggilan sampai akhir timestep.
    if crate::system_task_gen::has_strobe(design) {
        field_indent.push(&mut out);
        out.push_str(
            "// Skala `%t` ikut dibawa: milik modul pemanggil, bukan modul top (LRM §21.8).\n\
             strobe_pending: Vec<(&'static str, sv_runtime::TimeScale, \
             Vec<sv_runtime::FormatArg<MAX_WIDTH>>)>,\n",
        );
    }
    // LRM §23.2: driver membaca dua field ini setelah `initial` t=0 jalan
    // untuk memutuskan apakah VCD perlu ditulis.
    if crate::system_task_gen::has_dumpvars(design) {
        field_indent.push(&mut out);
        out.push_str("dump_on: bool,\n");
        field_indent.push(&mut out);
        out.push_str("dump_path: &'static str,\n");
    }
    indent.push(&mut out);
    out.push_str("}\n\n");

    out.push_str(&format!("impl {0} {{\n", struct_name));
    let inner = indent.child();

    write_new(design, &struct_name, &inner, &mut out);
    write_accessors(design, &inner, &mut out);
    write_eval_comb(design, &inner, &mut out);
    write_eval_seq(design, &inner, &mut out);
    write_sample_edge(design, &inner, &mut out);
    write_eval_initial(design, &inner, &mut out);
    write_is_finished(design, &inner, &mut out);
    write_time_now(design, &inner, &mut out);
    write_snapshot(&inner, &mut out);
    write_run_monitor(design, &inner, &mut out);
    write_run_strobe(design, &inner, &mut out);
    write_dump_accessors(design, &inner, &mut out);
    write_commit_pending(&inner, &mut out);

    inner.push(&mut out);
    out.push_str("}\n");
    out
}

/// Import runtime untuk satu design.
///
/// Path ditulis absolut (`::sv_runtime`) karena design dibungkus `mod <nama>`
/// dan modul SV boleh bernama apa saja — termasuk `sv_runtime`, yang kalau
/// tidak akan memblokir crate aslinya dan membuat `use` berubah jadi
/// `struct import is private`.
fn imports() -> &'static str {
    "use ::sv_runtime::Bits;\n\
     use ::sv_runtime::Logic;\n\
     use ::sv_runtime::PendingWrite;\n\
     use ::sv_runtime::SignalCell;\n\
     use ::sv_runtime::SimTime;\n\n"
}

fn write_new(design: &Design, struct_name: &str, inner: &Indent, out: &mut String) {
    let ada_initial = has_initial(design);
    let perlu_finish = ada_initial || crate::system_task_gen::has_finish(design);
    let ada_waktu = crate::time_scan::has_time(design);
    inner.push(out);
    out.push_str("pub fn new() -> Self {\n");
    let body = inner.child();
    body.push(out);
    out.push_str(&format!("let signal_count = {};\n", design.variables.len()));
    body.push(out);
    if design.variables.iter().any(|v| v.initial.is_some()) {
        out.push_str("let mut design = Self {\n");
    } else {
        out.push_str("Self {\n");
    }
    let fields = body.child();
    fields.push(out);
    // LRM §4.3.1: nilai awal variabel adalah `x`, bukan `0`. Memulai dari nol
    // membuat variabel yang belum pernah ditulis terbaca sebagai angka pasti,
    // padahal nilainya belum diketahui — dan seluruh logika 4-state berikutnya
    // jadi salah. Lebar logis sinyal tidak dipakai di sini: seluruh vektor
    // penyimpanan diisi `x`, termasuk bit di atas lebar logis yang tidak pernah
    // boleh dibaca.
    out.push_str(
        "signals: (0..signal_count).map(|_| SignalCell::new(Bits::all(Logic::X))).collect(),\n",
    );
    fields.push(out);
    out.push_str("pending: Vec::new(),\n");
    fields.push(out);
    out.push_str("sensitivity: vec![\n");
    for process in &design.processes {
        let list: Vec<String> = process
            .sensitivity
            .iter()
            .map(|item| item.signal.to_string())
            .collect();
        fields.push(out);
        out.push_str(&format!("{}vec![{}],\n", " ".repeat(8), list.join(", ")));
    }
    fields.push(out);
    out.push_str("    ],\n");
    if perlu_finish {
        fields.push(out);
        out.push_str("finished: false,\n");
    }
    if ada_initial {
        fields.push(out);
        out.push_str(&format!(
            "initial_pc: vec![0; {}],\n",
            crate::initial_step::segmen_design(design).len()
        ));
    }
    if perlu_edge_prev(design) {
        fields.push(out);
        out.push_str("edge_prev: vec![0; signal_count],\n");
    }
    if ada_waktu {
        fields.push(out);
        out.push_str("time_now: SimTime::ZERO,\n");
    }
    if crate::system_task_gen::uses_monitor_flag(design) {
        fields.push(out);
        out.push_str("monitor_fmt: \"\",\n");
        fields.push(out);
        out.push_str("monitor_args: Vec::new(),\n");
        fields.push(out);
        out.push_str("monitor_active: false,\n");
        if crate::system_task_gen::monitor_condition(design).is_some() {
            fields.push(out);
            out.push_str("monitor_cond: false,\n");
        }
    }
    if crate::system_task_gen::has_strobe(design) {
        fields.push(out);
        out.push_str("strobe_pending: Vec::new(),\n");
    }
    if crate::system_task_gen::has_dumpvars(design) {
        fields.push(out);
        out.push_str("dump_on: false,\n");
        fields.push(out);
        out.push_str("dump_path: \"\",\n");
    }
    if design.variables.iter().any(|v| v.initial.is_some()) {
        out.push_str("};\n");
        body.push(out);
        out.push_str("design.init_values();\n");
        body.push(out);
        out.push_str("design\n");
    } else {
        body.push(out);
        out.push_str("}\n");
    }
    inner.push(out);
    out.push_str("}\n\n");
    let _ = struct_name;

    // Nilai awal waktu nol ditulis lewat method terpisah supaya ekspresi
    // inisialisasi boleh membaca sinyal lain lewat `self.signals[..]`.
    if design.variables.iter().any(|v| v.initial.is_some()) {
        inner.push(out);
        out.push_str("fn init_values(&mut self) {\n");
        let init_body = inner.child();
        init_body.push(out);
        for var in &design.variables {
            if let Some(expr) = &var.initial {
                out.push_str(&format!("self.signals[{}] = ", var.signal_id));
                let mut kode = String::new();
                let eks_indent = Indent::new();
                crate::expr_gen::write_expr(expr, &mut kode, &eks_indent);
                out.push_str("SignalCell::new(");
                out.push_str(&kode);
                out.push_str(");\n");
            }
        }
        inner.push(out);
        out.push_str("}\n\n");
    }
}

fn write_accessors(design: &Design, inner: &Indent, out: &mut String) {
    for var in &design.variables {
        let width = var.data_type.width;
        let field = var.name.to_lowercase();

        inner.push(out);
        out.push_str(&format!("pub fn {}(&self) -> Bits<{}> {{\n", field, width));
        inner.child().push(out);
        out.push_str(&format!(
            "self.signals[{}].read().resize::<{}>()\n",
            var.signal_id, width
        ));
        inner.push(out);
        out.push_str("}\n\n");

        inner.push(out);
        out.push_str(&format!(
            "pub fn set_{}(&mut self, value: Bits<{}>) {{\n",
            field, width
        ));
        inner.child().push(out);
        out.push_str(&format!(
            "self.signals[{}].write(value.widen::<MAX_WIDTH>());\n",
            var.signal_id
        ));
        inner.push(out);
        out.push_str("}\n\n");
    }
}

fn write_eval_comb(design: &Design, inner: &Indent, out: &mut String) {
    let combinational: Vec<_> = design
        .processes
        .iter()
        .filter(|p| p.kind == ProcessKind::Combinational)
        .collect();

    inner.push(out);
    out.push_str("pub fn eval_comb(&mut self) {\n");
    let body = inner.child();
    for process in &combinational {
        body.push(out);
        out.push_str(&format!("// {}\n", process.name));
        write_statements(&process.body, out, &body);
    }
    inner.push(out);
    out.push_str("}\n\n");
}

fn write_eval_seq(design: &Design, inner: &Indent, out: &mut String) {
    let sequential: Vec<_> = design
        .processes
        .iter()
        .filter(|p| p.kind == ProcessKind::Sequential)
        .collect();

    inner.push(out);
    // Tanpa proses sekuensial, parameter `clock` tak terpakai; diganti
    // garis bawah agar hasil generate bebas warning `unused_variables`.
    let arg_clock = if sequential.is_empty() {
        "_clock"
    } else {
        "clock"
    };
    out.push_str(&format!(
        "pub fn eval_seq(&mut self, {}: usize) {{\n",
        arg_clock
    ));
    let body = inner.child();
    for process in &sequential {
        let clock_id = process.sensitivity.first().map(|s| s.signal).unwrap_or(0);
        body.push(out);
        out.push_str(&format!("// {} (clock = {})\n", process.name, clock_id));
        body.push(out);
        // LRM §9.7: selain evaluasi langkah utama pada clock pertama, proses
        // dengan event gabungan (mis. async reset) juga dievaluasi saat edge
        // nyata terjadi pada salah satu sinyal sensitivitasnya.
        let syarat = if process.sensitivity.len() > 1 {
            let events: Vec<sv_ir::process::EventItem> = process
                .sensitivity
                .iter()
                .map(|s| sv_ir::process::EventItem {
                    edge: s.edge,
                    signal: s.signal,
                })
                .collect();
            format!("clock == {} || ({})", clock_id, edge_test(&events))
        } else {
            format!("clock == {}", clock_id)
        };
        out.push_str(&format!("if {} {{\n", syarat));
        write_statements(&process.body, out, &body.child());
        body.push(out);
        out.push_str("}\n");
    }
    inner.push(out);
    out.push_str("}\n\n");
}

/// True bila design butuh field `edge_prev` dan method `sample_edge`.
///
/// Pemicu: menunggu edge di blok `initial`, atau proses sekuensial dengan
/// event control gabungan (LRM §9.7) yang diuji terhadap nilai edge sebelumnya.
pub fn perlu_edge_prev(design: &Design) -> bool {
    crate::initial_step::total_tunggu(design) > 0 || ada_event_gabungan(design)
}

/// True bila ada proses sekuensial dengan lebih dari satu item sensitivitas.
fn ada_event_gabungan(design: &Design) -> bool {
    design
        .processes
        .iter()
        .filter(|p| p.kind == ProcessKind::Sequential)
        .any(|p| p.sensitivity.len() > 1)
}

/// Tulis method `sample_edge` bila design menyimpan `edge_prev`.
///
/// LRM §9.7: nilai sekarang dibandingkan dengan nilai langkah sebelumnya
/// untuk mengenali posedge/negedge, jadi tiap sinyal yang diawasi harus
/// disampel di akhir setiap langkah.
fn write_sample_edge(design: &Design, inner: &Indent, out: &mut String) {
    if !perlu_edge_prev(design) {
        return;
    }
    inner.push(out);
    out.push_str("/// Remember the watched signal values at the end of this step.\n");
    out.push_str("pub fn sample_edge(&mut self) {\n");
    let sample_body = inner.child();
    for sinyal in sinyal_disampel(design) {
        sample_body.push(out);
        out.push_str(&format!(
            "    self.edge_prev[{}] = self.signals[{}].read().to_u64() & 1;\n",
            sinyal, sinyal
        ));
    }
    inner.push(out);
    out.push_str("}\n\n");
}

/// Tulis method `snapshot` untuk mendeteksi perubahan sinyal bagi `$monitor`.
fn write_snapshot(inner: &Indent, out: &mut String) {
    inner.push(out);
    out.push_str("pub fn snapshot(&self) -> Vec<u64> {\n");
    let body = inner.child();
    body.push(out);
    out.push_str("self.signals.iter().map(|s| s.read().to_u64()).collect()\n");
    inner.push(out);
    out.push_str("}\n\n");
}

/// Tulis method `refresh_monitor_args` dan `run_monitor` untuk `$monitor`.
///
/// Nilai argumen dievaluasi ulang setiap pemancaran; kalau hanya disimpan
/// sekali saat pendaftaran, `$monitor` akan menampilkan nilai basi.
fn write_run_monitor(design: &Design, inner: &Indent, out: &mut String) {
    if !crate::system_task_gen::uses_monitor_flag(design) {
        return;
    }
    let Some(task) = crate::system_task_gen::find_monitor(design) else {
        // Hanya `$monitoron`/`$monitoroff`: format argumen tidak pernah diisi.
        inner.push(out);
        out.push_str("pub fn run_monitor(&mut self) {\n");
        let body = inner.child();
        body.push(out);
        out.push_str("let _ = self.monitor_active;\n");
        inner.push(out);
        out.push_str("}\n\n");
        return;
    };

    inner.push(out);
    out.push_str("fn refresh_monitor_args(&mut self) {\n");
    let body = inner.child();
    body.push(out);
    out.push_str("self.monitor_args = vec![\n");
    crate::system_task_gen::write_monitor_args(&task.args, out, &body);
    // Syarat `$monitor if` dievaluasi ulang tiap pemancaran, sama seperti
    // argumennya, karena bisa bergantung pada sinyal yang berubah (LRM §20.2).
    if let Some(kondisi) = &task.condition {
        body.push(out);
        out.push_str("self.monitor_cond = ");
        crate::expr_gen::write_truthy_pub(kondisi, out, &body);
        out.push_str(";\n");
    }
    inner.push(out);
    out.push_str("}\n\n");

    inner.push(out);
    out.push_str("pub fn run_monitor(&mut self) {\n");
    let body = inner.child();
    body.push(out);
    out.push_str("if self.monitor_active {\n");
    let dalam = body.child();
    dalam.push(out);
    out.push_str("self.refresh_monitor_args();\n");
    // Tanpa syarat, `$monitor` selalu mencetak; dengan syarat, hanya saat
    // syaratnya bernilai benar (LRM §20.2).
    let ada_syarat = task.condition.is_some();
    if ada_syarat {
        dalam.push(out);
        out.push_str("if self.monitor_cond {\n");
    }
    let cetak = dalam.child();
    cetak.push(out);
    // Skala `%t` milik modul yang memuat `$monitor` (LRM §20.4 + §21.8).
    out.push_str(&format!(
        "print!(\"{{}}\", sv_runtime::sv_format_args({:?}, &self.monitor_args, {}));\n",
        crate::system_task_gen::format_monitor(&task.args),
        crate::time_gen::literal_time_scale_dari(task.time_scale)
    ));
    if ada_syarat {
        dalam.push(out);
        out.push_str("}\n");
    }
    body.push(out);
    out.push_str("}\n");
    inner.push(out);
    out.push_str("}\n\n");
}

/// Tulis method `run_strobe` untuk mencetak antrean `$strobe` di akhir timestep.
fn write_run_strobe(design: &Design, inner: &Indent, out: &mut String) {
    if !crate::system_task_gen::has_strobe(design) {
        return;
    }
    inner.push(out);
    out.push_str("pub fn run_strobe(&mut self) {\n");
    let body = inner.child();
    body.push(out);
    out.push_str("for (__fmt, __skala, __args) in std::mem::take(&mut self.strobe_pending) {\n");
    let dalam = body.child();
    dalam.push(out);
    out.push_str("print!(\"{}\", sv_runtime::sv_format_args(__fmt, &__args, __skala));\n");
    body.push(out);
    out.push_str("}\n");
    inner.push(out);
    out.push_str("}\n\n");
}

/// Tulis accessor `dump_requested` dan `dump_path` untuk driver VCD.
///
/// LRM §23.2: pencatatan baru aktif setelah `$dumpvars` dipanggil, sehingga
/// driver menanyakan statusnya setelah blok `initial` t=0 dievaluasi.
fn write_dump_accessors(design: &Design, inner: &Indent, out: &mut String) {
    if !crate::system_task_gen::has_dumpvars(design) {
        return;
    }
    inner.push(out);
    out.push_str("/// True bila `$dumpvars` sudah dipanggil (LRM §23.2).\n");
    out.push_str("pub fn dump_requested(&self) -> bool {\n");
    out.push_str("    self.dump_on\n");
    out.push_str("}\n\n");
    inner.push(out);
    out.push_str("/// Nama berkas dari `$dumpfile`; kosong bila tidak pernah dipanggil.\n");
    out.push_str("pub fn dump_path(&self) -> &'static str {\n");
    out.push_str("    self.dump_path\n");
    out.push_str("}\n\n");
}

/// Tulis method `eval_initial` bila ada blok `initial`.
///
/// LRM §15.2: blok `initial` berjalan sekali pada waktu nol, sehingga tidak
/// punya sensitivitas seperti proses combinational maupun sekuensial.
fn write_eval_initial(design: &Design, inner: &Indent, out: &mut String) {
    if !has_initial(design) {
        return;
    }
    // Setiap proses initial dipecah pada batas `#delay`, lalu setiap segmen
    // dijalankan pada langkah waktunya sendiri (LRM §11.2).
    let segmen = crate::initial_step::segmen_design(design);

    inner.push(out);
    out.push_str(&format!(
        "pub const INITIAL_STEPS: usize = {};\n\n",
        crate::initial_step::langkah_driver(design)
    ));

    let ada_tunggu = crate::initial_step::total_tunggu(design) > 0;

    inner.push(out);
    out.push_str("pub fn eval_initial(&mut self, step: usize) {\n");
    let body = inner.child();
    body.push(out);
    if ada_tunggu {
        // Segmen dijalankan menurut penunjuk tiap proses, bukan menurut
        // indeks langkah, supaya segmen yang menunggu edge bisa dicoba lagi.
        body.push(out);
        out.push_str("    let _ = step;\n");
        for (index, segments) in segmen.iter().enumerate() {
            // Rantai `if/else if` wajib: hanya satu segmen per proses yang
            // boleh jalan pada satu langkah waktu.
            for (urut, segment) in segments.iter().enumerate() {
                let awal = if urut == 0 { "if" } else { "} else if" };
                let events = await_event_control(segment);
                let syarat_urut = format!("self.initial_pc[{}] == {}", index, urut);
                let header = match events {
                    Some(events) => format!("{} {} && {} ", awal, syarat_urut, edge_test(events)),
                    None => format!("{} {} ", awal, syarat_urut),
                };
                body.push(out);
                out.push_str(&format!("    // {} segmen {}\n", nama_proses(index), urut));
                body.push(out);
                out.push_str(&format!("    {} {{\n", header));
                let arm = body.child();
                // Bodynya ditulis sebagai daftar statement; untuk segmen event
                // control statement `@(...)`-nya sendiri tidak diulang.
                let statements: &[sv_ir::process::Statement] = if events.is_some() {
                    &segment[1..]
                } else {
                    segment.as_slice()
                };
                if !statements.is_empty() {
                    write_statements(statements, out, &arm);
                }
                arm.push(out);
                out.push_str(&format!(
                    "        self.initial_pc[{}] = {};\n",
                    index,
                    urut + 1
                ));
                body.push(out);
                if urut + 1 == segments.len() {
                    out.push_str("    }\n");
                }
            }
        }
        inner.push(out);
        out.push_str("}\n\n");
        // `is_finished` ditulis terpisah oleh `write_is_finished`, supaya
        // tidak ter-emit dua kali pada jalur yang menunggu edge.
        return;
    }

    body.push(out);
    out.push_str("    match step {\n");
    for step in 0..crate::initial_step::jumlah_langkah(design) {
        let lanjutan: Vec<(String, &[sv_ir::process::Statement])> = segmen
            .iter()
            .enumerate()
            .filter_map(|(index, segments)| {
                segments
                    .get(step)
                    .filter(|segmen| !segmen.is_empty())
                    .map(|segmen| (nama_proses(index), segmen.as_slice()))
            })
            .collect();
        if lanjutan.is_empty() {
            continue;
        }
        body.push(out);
        out.push_str(&format!("        {} => {{\n", step));
        let arm = body.child();
        for (nama, statements) in lanjutan {
            arm.push(out);
            out.push_str(&format!("// {}\n", nama));
            write_statements(statements, out, &arm);
        }
        body.push(out);
        out.push_str("        }\n");
    }
    body.push(out);
    out.push_str("        _ => {}\n");
    // Tutup `match` lalu fungsi; dua kurung wajib agar Rust yang dihasilkan
    // bisa dikompilasi.
    body.push(out);
    out.push_str("    }\n");
    inner.push(out);
    out.push_str("}\n\n");

    inner.push(out);
}

/// Tulis method `is_finished` bila design punya blok `initial` atau memanggil
/// `$finish` pada proses mana pun (LRM §20.3).
fn write_is_finished(design: &Design, inner: &Indent, out: &mut String) {
    if !has_initial(design) && !crate::system_task_gen::has_finish(design) {
        return;
    }
    inner.push(out);
    out.push_str("pub fn is_finished(&self) -> bool {\n");
    inner.child().push(out);
    out.push_str("self.finished\n");
    inner.push(out);
    out.push_str("}\n\n");
}

/// Waktu simulasi sekarang; dipakai driver untuk timestamp VCD.
///
/// Field `time_now` hanya dibangkitkan bila design memakai waktu, jadi method
/// ini ikut hanya dibuat pada design itu — memanggilnya pada design tanpa
/// delay akan jadi error kompilasi, bukan diam-diam mengembalikan nol.
fn write_time_now(design: &Design, inner: &Indent, out: &mut String) {
    if !crate::time_scan::has_time(design) {
        return;
    }
    inner.push(out);
    out.push_str("pub fn time_now(&self) -> SimTime {\n");
    inner.child().push(out);
    out.push_str("self.time_now\n");
    inner.push(out);
    out.push_str("}\n\n");
}

/// Sinyal yang diawasi `@(...)` pada blok `initial`, urut dan tanpa duplikat.
fn sinyal_terawasi(design: &Design) -> Vec<u32> {
    let mut out: Vec<u32> = Vec::new();
    for segments in crate::initial_step::segmen_design(design) {
        for segment in segments {
            for sinyal in crate::initial_step::sinyal_event_control(&segment) {
                if !out.contains(&sinyal) {
                    out.push(sinyal);
                }
            }
        }
    }
    out
}

/// Seluruh sinyal yang nilainya harus disimpan `sample_edge`.
///
/// Gabungan sinyal yang diawasi blok `initial` dan sinyal sensitivitas proses
/// sekuensial dengan event gabungan; keduanya dibandingkan dengan langkah
/// sebelumnya untuk mengenali edge (LRM §9.7).
fn sinyal_disampel(design: &Design) -> Vec<u32> {
    let mut out = sinyal_terawasi(design);
    for process in design
        .processes
        .iter()
        .filter(|p| p.kind == ProcessKind::Sequential)
    {
        if process.sensitivity.len() > 1 {
            for item in &process.sensitivity {
                if !out.contains(&item.signal) {
                    out.push(item.signal);
                }
            }
        }
    }
    out
}

/// Sinyal dan sisi edge dari statement `@(...)` di awal sebuah segmen.
fn await_event_control(
    segment: &[sv_ir::process::Statement],
) -> Option<&[sv_ir::process::EventItem]> {
    match segment.first() {
        Some(sv_ir::process::Statement::EventControl { events, .. }) => Some(events.as_slice()),
        _ => None,
    }
}

/// Gabungkan seluruh item event jadi satu kondisi OR (LRM §9.7).
///
/// `@(posedge clk or negedge rst)` memicu bila salah satu edge terjadi.
fn edge_test(events: &[sv_ir::process::EventItem]) -> String {
    if events.is_empty() {
        return "false".to_string();
    }
    events
        .iter()
        .map(edge_test_item)
        .collect::<Vec<String>>()
        .join(" || ")
}

/// Kondisi Rust untuk satu item event.
fn edge_test_item(item: &sv_ir::process::EventItem) -> String {
    use sv_ir::process::EdgeSensitivity;
    let prev = format!("self.edge_prev[{}] & 1", item.signal);
    let now = format!("self.signals[{}].read().to_u64() & 1", item.signal);
    match item.edge {
        EdgeSensitivity::Posedge => format!("{} == 0 && {} == 1", prev, now),
        EdgeSensitivity::Negedge => format!("{} == 1 && {} == 0", prev, now),
        EdgeSensitivity::AnyChange => format!("{} != {}", prev, now),
    }
}

// LRM §9.7: nilai sekarang dibaca langsung dari sel sinyal, sedangkan nilai
// sebelumnya disimpan oleh `sample_edge`.

/// Nama proses untuk komentar pada segmen langkah waktu.
fn nama_proses(index: usize) -> String {
    format!("initial[{}]", index)
}

/// True bila design punya setidaknya satu proses `initial`.
pub fn has_initial(design: &Design) -> bool {
    design
        .processes
        .iter()
        .any(|p| p.kind == ProcessKind::Initial)
}

fn write_commit_pending(inner: &Indent, out: &mut String) {
    inner.push(out);
    out.push_str("pub fn commit_pending(&mut self) {\n");
    let body = inner.child();
    body.push(out);
    out.push_str("for write in std::mem::take(&mut self.pending) {\n");
    body.child().push(out);
    out.push_str("self.signals[write.target].write_masked(write.value, write.mask);\n");
    body.push(out);
    out.push_str("}\n");
    inner.push(out);
    out.push_str("}\n\n");
}

/// Lebar penyimpanan `Bits<MAX_WIDTH>` untuk seluruh design.
///
/// Hanya melihat lebar variabel **belum cukup**: nilai yang lebih lebar muncul
/// juga dari konstanta dan dari lebar tipe pada ekspresi — `$bits(...)` selalu
/// konstanta 32-bit, dan `typedef logic [127:0] wide_t` menghasilkan cast ke
/// 128 bit walaupun tidak ada satu pun sinyal 128-bit di design. Karena
/// `Bits::set` diam-diam mengabaikan indeks di luar `N`, jadi baik konstanta
/// maupun bit perluasan cast akan hilang tanpa error — dan pemformat `%h`
/// meng-zero-pad hasilnya, jadi nilainya terlihat "benar" tapi salah.
///
/// Semua lebar yang muncul di ekspresi ikut dipetakan supaya tidak ada nilai
/// yang terpotong.
fn max_width(design: &Design) -> u32 {
    let mut lebar = design
        .variables
        .iter()
        .map(|v| v.data_type.width)
        .max()
        .unwrap_or(1)
        .max(1);

    // `$time` bertipe 64-bit; kalau design hanya punya sinyal sempit,
    // nilainya akan terpangkas oleh masker `Bits<MAX_WIDTH>`.
    if crate::time_scan::has_time(design) {
        lebar = lebar.max(64);
    }

    let mut ekspresi = Vec::new();
    for process in &design.processes {
        kumpulkan_list(&process.body, &mut ekspresi);
    }
    for expr in &ekspresi {
        lebar = lebar.max(max_width_expr(expr));
    }
    // Lebar argumen pada pemanggilan system task juga penting: `$display("%h",
    // word_t'(x))` menyimpan lebar logis tipe pada `FormatArg`, dan
    // `to_hex_str` membaca sebanyak itu digit — lebih sedikit bit daripada
    // yang diminta berarti digit atas tercetak sebagai `x`/`z` atau hilang.
    for process in &design.processes {
        for stmt in &process.body {
            kumpulkan_argumen(stmt, &mut lebar);
        }
    }
    lebar
}

/// Perbarui `lebar` dengan lebar tipe argumen pada system task.
///
/// Berbeda dari ekspresi biasa, konstanta di sini **tidak** boleh dipangkas ke
/// bit significant: `$display("%h", 32'hDEADBEEF)` meminta 8 digit heksa
/// melalui `FormatArg::width`, dan hanya 4 bit yang bernilai. Memangkas ke 4
/// membuat 4 digit atas tercetak `0000` — benar secara nilai, salah secara
/// tampilan.
fn kumpulkan_argumen(stmt: &Statement, lebar: &mut u32) {
    match stmt {
        Statement::SystemTask {
            args, condition, ..
        } => {
            for arg in args {
                if let sv_ir::expr::SystemArg::Value(expr) = arg {
                    *lebar = (*lebar).max(lebar_logis_penuh(expr));
                }
            }
            if let Some(cond) = condition {
                *lebar = (*lebar).max(lebar_logis_penuh(cond));
            }
        }
        Statement::Assign { assignment, .. } => {
            *lebar = (*lebar).max(lebar_logis_penuh(&assignment.value));
        }
        Statement::If {
            condition,
            then_branch,
            else_branch,
            ..
        } => {
            *lebar = (*lebar).max(lebar_logis_penuh(condition));
            for s in then_branch.iter().chain(else_branch.iter()) {
                kumpulkan_argumen(s, lebar);
            }
        }
        Statement::Case { selector, arms, .. } => {
            *lebar = (*lebar).max(lebar_logis_penuh(selector));
            for arm in arms {
                for label in &arm.labels {
                    *lebar = (*lebar).max(lebar_logis_penuh(label));
                }
                for s in &arm.body {
                    kumpulkan_argumen(s, lebar);
                }
            }
        }
        Statement::For {
            init,
            condition,
            step,
            body,
            ..
        } => {
            *lebar = (*lebar)
                .max(lebar_logis_penuh(&init.value))
                .max(lebar_logis_penuh(condition))
                .max(lebar_logis_penuh(&step.value));
            for s in body {
                kumpulkan_argumen(s, lebar);
            }
        }
        Statement::Repeat { count, body, .. } => {
            *lebar = (*lebar).max(lebar_logis_penuh(count));
            for s in body {
                kumpulkan_argumen(s, lebar);
            }
        }
        Statement::While {
            condition, body, ..
        } => {
            *lebar = (*lebar).max(lebar_logis_penuh(condition));
            for s in body {
                kumpulkan_argumen(s, lebar);
            }
        }
        Statement::Block { body, .. } | Statement::EventControl { body, .. } => {
            for s in body {
                kumpulkan_argumen(s, lebar);
            }
        }
        Statement::Delay { amount, body, .. } => {
            *lebar = (*lebar).max(lebar_logis_penuh(amount));
            kumpulkan_argumen(body, lebar);
        }
        Statement::Noop { .. } => {}
    }
}

/// Lebar logis penuh satu ekspresi: konstanta memakai lebar tipenya, bukan
/// hanya bit yang significance-nya.
fn lebar_logis_penuh(expr: &Expr) -> u32 {
    expr.data_type().width
}

/// Lebar terbesar yang muncul pada satu ekspresi beserta seluruh anaknya.
fn max_width_expr(expr: &Expr) -> u32 {
    // Konstanta dikecualikan dari lebar tipenya: LRM §5.7.1 memberi literal
    // desimal polos lebar 32, tapi `0` hanya butuh satu digit. Mengambil
    // `data_type().width` untuk konstanta akan memaksa `MAX_WIDTH` jadi 32
    // hanya karena ada `== 0` di design yang sinyalnya 8 bit.
    let lebar_tipe = match expr {
        Expr::Const { .. } => 0,
        other => other.data_type().width,
    };
    lebar_tipe.max(match expr {
        Expr::Bin { lhs, rhs, .. } => max_width_expr(lhs).max(max_width_expr(rhs)),
        Expr::Un { operand, .. } | Expr::Cast { operand, .. } => max_width_expr(operand),
        // `Select`/`Index` membaca base pada posisi bit yang ditentukan lebarnya,
        // jadi lebar logis base WAJIB ikut dihitung. Kalau tidak, `MAX_WIDTH`
        // bisa lebih kecil dari lebar base — helper runtime lalu memakai
        // `Bits::<MAX_WIDTH>` dan indeks di atas `MAX_WIDTH` membaca bit yang
        // tidak ada (`Logic::X`) padahal nilainya ada di sinyal.
        Expr::Select { base, .. } => max_width_expr(base).max(base.data_type().width),
        Expr::Ternary {
            condition,
            when_true,
            when_false,
            ..
        } => max_width_expr(condition)
            .max(max_width_expr(when_true))
            .max(max_width_expr(when_false)),
        Expr::Concat { items, .. } => items.iter().map(max_width_expr).max().unwrap_or(0),
        Expr::Replicate { value, .. } => max_width_expr(value),
        Expr::Index { base, index, .. } => max_width_expr(base)
            .max(max_width_expr(index))
            .max(base.data_type().width),
        Expr::SignalRef { .. } | Expr::SimTime { .. } => 0,
        // Konstanta hanya butuh ruang sampai bit tertinggi yang benar-benar
        // bisa bernilai — bukan sepanjang lebar tipenya. LRM §5.7.1 memberi
        // literal desimal polos lebar 32, tapi `0` tetap muat di 1 bit; memaksa
        // `MAX_WIDTH` jadi 32 hanya karena ada `== 0` akan membuat design 8-bit
        // memakai penyimpanan 32-bit tanpa alasan.
        //
        // `X`/`Z` ikut dihitung karena keduanya disimpan sebagai digit, bukan
        // sebagai nilai.
        Expr::Const {
            value,
            unknown_mask,
            zmask,
            ..
        } => significant_bits(*value)
            .max(significant_bits(*unknown_mask))
            .max(significant_bits(*zmask)),
    })
}

/// Bit tertinggi yang mungkin bernilai satu, dihitung satu-based.
///
/// Nol menghasilkan 1 karena vektor harus tetap bisa menyimpan satu digit.
fn significant_bits(value: u64) -> u32 {
    (64 - value.leading_zeros()).max(1)
}

/// Kumpulkan seluruh ekspresi yang muncul pada satu statement.
fn kumpulkan_stmt(stmt: &Statement, out: &mut Vec<Expr>) {
    match stmt {
        Statement::Assign { assignment, .. } => {
            out.push(assignment.value.clone());
        }
        Statement::Case { selector, arms, .. } => {
            out.push(selector.clone());
            for arm in arms {
                for label in &arm.labels {
                    out.push(label.clone());
                }
                kumpulkan_list(&arm.body, out);
            }
        }
        Statement::If {
            condition,
            then_branch,
            else_branch,
            ..
        } => {
            out.push(condition.clone());
            kumpulkan_list(then_branch, out);
            kumpulkan_list(else_branch, out);
        }
        Statement::For {
            init,
            condition,
            step,
            body,
            ..
        } => {
            // `init` dan `step` adalah `Assignment`, jadi ekspresinya diambil
            // lewat `.value`.
            out.push(init.value.clone());
            out.push(condition.clone());
            out.push(step.value.clone());
            kumpulkan_list(body, out);
        }
        Statement::Repeat { count, body, .. } => {
            out.push(count.clone());
            kumpulkan_list(body, out);
        }
        Statement::While {
            condition, body, ..
        } => {
            out.push(condition.clone());
            kumpulkan_list(body, out);
        }
        Statement::SystemTask {
            args, condition, ..
        } => {
            for arg in args {
                if let sv_ir::expr::SystemArg::Value(expr) = arg {
                    out.push(expr.clone());
                }
            }
            if let Some(cond) = condition {
                out.push(cond.clone());
            }
        }
        Statement::Block { body, .. } | Statement::EventControl { body, .. } => {
            kumpulkan_list(body, out);
        }
        Statement::Delay { amount, body, .. } => {
            out.push(amount.clone());
            kumpulkan_stmt(body, out);
        }
        Statement::Noop { .. } => {}
    }
}

fn kumpulkan_list(body: &[Statement], out: &mut Vec<Expr>) {
    for stmt in body {
        kumpulkan_stmt(stmt, out);
    }
}

pub fn to_struct_name(name: &str) -> String {
    let mut out = String::new();
    let mut capitalize = true;
    for ch in name.chars() {
        if ch == '_' || ch == '.' {
            capitalize = true;
        } else if capitalize {
            out.extend(ch.to_uppercase());
            capitalize = false;
        } else {
            out.push(ch);
        }
    }
    out
}

/// Nama file modul Rust untuk satu design.
///
/// Nama file tidak boleh bentrok dengan kata kunci Rust dan tetap dipakai
/// sebagai identifier modul di program hasil generate — lihat
/// [`crate::module_name`] untuk versi yang aman dipakai sebagai `mod`.
pub fn to_module_name(name: &str) -> String {
    crate::module_name::module_name(name)
}
