// Tanggung jawab: generate program driver simulasi (termasuk capture VCD).
use std::path::Path;
use sv_ir::design::{PortDirection, PortInfo};
use sv_ir::process::ProcessKind;
use sv_ir::Design;

/// Generate driver; bila `vcd` diisi, hasilkan driver dengan capture waveform.
pub fn generate_driver(design: &Design, steps: usize, vcd: Option<&Path>) -> String {
    // `main` tidak boleh punya parameter (`error[E0601]`), dan `STEPS` tidak
    // boleh dideklarasikan di dua driver sekaligus, jadi nilainya dibawa lewat
    // pemanggilan fungsi.
    let module = sv_codegen_rust::to_module_name(&design.name);
    let fn_name = "jalankan_design";
    let body = match vcd {
        Some(path) => generate_vcd_driver_named(design, steps, path, fn_name, &module),
        None => generate_plain_driver_named(design, steps, fn_name, &module),
    };
    format!("{body}\nfn main() {{\n    {fn_name}({steps});\n}}\n")
}

/// Header untuk satu modul root di dalam program banyak-root.
///
/// Setiap modul root dielaborasi sebagai design sendiri (LRM §23.1), jadi
/// tiap driver menjadi fungsi terpisah dan `main` memanggilnya berurutan.
/// Versi lama hanya mengelaborasi modul terakhir, jadi output modul root lain
/// hilang tanpa pesan.
///
/// `STEPS` tidak dideklarasikan di sini: program banyak-root memanggil
/// beberapa driver dan deklarasi it'll berkonflik di lingkup atas. Nilai
/// langkah dibawa sebagai parameter ke tiap driver.
fn header_fungsi(struct_name: &str, fn_name: &str, _steps: usize) -> String {
    format!(
        "// Generated by cargo-sv. Jangan edit manual.\n\
         fn {fn_name}(STEPS: usize) {{\n    let mut design = {}::new();\n",
        struct_name
    )
}

/// Path struct design: `modul::Struct`.
///
/// Tiap design ditulis sebagai module Rust sendiri supaya dua design dengan
/// `MAX_WIDTH` yang sama tidak bentrok di lingkup atas — digabung apa adanya,
/// kode hasil generate gagal dengan `the name MAX_WIDTH is defined multiple
/// times`.
fn qualify(module: &str, struct_name: &str) -> String {
    format!("{module}::{struct_name}")
}

/// Driver untuk banyak modul root: `main` memanggil tiap driver berurutan.
///
/// Tiap design punya waktu simulasi sendiri, jadi tidak ada saling ganggu
/// antar-root; yang penting keduanya benar-benar dijalankan.
pub fn generate_multi_driver(designs: &[(&str, &Design, Option<&Path>)], steps: usize) -> String {
    let mut out = String::from("// Generated by cargo-sv. Jangan edit manual.\n\n");
    for (nama, design, path) in designs {
        // `nama` sudah berupa module Rust hasil qualify; driver memakai
        // struct yang sama persis.
        let fn_name = format!("jalankan_{}", nama);
        let driver = match path {
            Some(path) => generate_vcd_driver_named(design, steps, path, &fn_name, nama),
            None => generate_plain_driver_named(design, steps, &fn_name, nama),
        };
        out.push_str(&driver);
        out.push('\n');
    }
    out.push_str("fn main() {\n");
    for (nama, _, _) in designs {
        out.push_str(&format!("    jalankan_{nama}({steps});\n"));
    }
    out.push_str("}\n");
    out
}

/// Driver tanpa VCD: set input nol, settle combinational, opsional clock.
fn generate_plain_driver_named(
    design: &Design,
    steps: usize,
    fn_name: &str,
    module: &str,
) -> String {
    let struct_name = qualify(module, &sv_codegen_rust::to_struct_name(&design.name));
    let mut out = header_fungsi(&struct_name, fn_name, steps);

    for port in input_ports(design) {
        out.push_str(&format!(
            "    design.set_{}(Bits::zero());\n",
            port.name.to_lowercase()
        ));
    }

    out.push_str("\n    // Settle combinational logic\n");
    out.push_str("    for _ in 0..STEPS {\n");
    out.push_str("        design.eval_comb();\n");
    out.push_str("        design.commit_pending();\n");
    out.push_str("    }\n\n");

    // LRM §15.2/§11.2: blok `initial` dipecah pada batas `#delay`. Setiap
    // segmen dijalankan pada langkah waktunya sendiri; di antara segmen,
    // logika combinational settle dan edge clock dievaluasi supaya proses
    // lain benar-benar melihat keadaan di waktu yang sama.
    // LRM §9.7: `edge_prev` disampel tiap langkah bila ada tunggu edge di
    // `initial` atau proses sekuensial dengan event control gabungan.
    let perlu_prev = sv_codegen_rust::module_gen::perlu_edge_prev(design);
    if sv_codegen_rust::module_gen::has_initial(design) {
        let clock_id = clock_signal_id(design);
        // LRM §9.7: `@(posedge clk)` hanya boleh lanjut kalau clock benar-benar
        // berubah, jadi clock ditoggle tiap langkah pada desain yang menunggu.
        let ada_tunggu = sv_codegen_rust::initial_step::total_tunggu(design) > 0;
        if ada_tunggu {
            if let Some((cf, cw)) = &clock_var(design) {
                out.push_str(&format!(
                    "    design.set_{}(Bits::<{}>::from_u64(0));\n",
                    cf, cw
                ));
            }
            out.push_str("    design.eval_initial(0);\n");
            out.push_str("    design.commit_pending();\n");
            out.push_str("    design.eval_comb();\n");
            out.push_str("    design.commit_pending();\n");
            if perlu_prev {
                out.push_str("    design.sample_edge();\n");
            }
        } else {
            out.push_str("    design.eval_initial(0);\n");
            out.push_str("    design.commit_pending();\n");
            out.push_str("    design.eval_comb();\n");
            out.push_str("    design.commit_pending();\n");
        }
        // Macro `$monitor` harus dideklarasikan sebelum dipakai (Rust macro
        //_rules bersifat tekstual), jadi diletakkan sebelum loop langkah.
        write_monitor_driver(
            sv_codegen_rust::system_task_gen::has_monitor(design),
            &mut out,
        );
        out.push_str(&format!(
            "    for __step in 1..{}::INITIAL_STEPS {{\n",
            struct_name
        ));
        if ada_tunggu {
            if let Some((cf, cw)) = &clock_var(design) {
                out.push_str(&format!(
                    "        design.set_{}(Bits::<{}>::from_u64((__step % 2) as u64));\n",
                    cf, cw
                ));
            }
        }
        out.push_str("        design.eval_initial(__step);\n");
        out.push_str("        design.commit_pending();\n");
        // LRM §20.3: `$finish` menghentikan simulasi. Bila segmen `initial`
        // yang baru saja jalan memanggil `$finish`, proses sekuensial tak
        // boleh lagi dievaluasi pada langkah yang sama.
        if sv_codegen_rust::system_task_gen::has_finish(design) {
            out.push_str("        if design.is_finished() {\n");
            out.push_str("            break;\n");
            out.push_str("        }\n");
        }
        out.push_str("        design.eval_comb();\n");
        out.push_str("        design.commit_pending();\n");
        match clock_id {
            Some(id) => {
                out.push_str(&format!("        design.eval_seq({});\n", id));
                out.push_str("        design.commit_pending();\n");
            }
            None => out.push_str("        // tanpa proses sekuensial pada design ini\n"),
        }
        if sv_codegen_rust::system_task_gen::has_finish(design) {
            out.push_str("        if design.is_finished() {\n");
            out.push_str("            break;\n");
            out.push_str("        }\n");
        }
        if sv_codegen_rust::system_task_gen::uses_monitor_flag(design) {
            out.push_str("        pantau_monitor!();\n");
        }
        // LRM §20.3: `$strobe` cetak di akhir timestep, setelah semua proses.
        if sv_codegen_rust::system_task_gen::has_strobe(design) {
            out.push_str("        design.run_strobe();\n");
        }
        // Nilai sinyal yang diawasi disimpan untuk langkah berikutnya.
        if perlu_prev {
            out.push_str("        design.sample_edge();\n");
        }
        out.push_str("    }\n\n");
    }

    if let Some(clock) = clock_signal_id(design) {
        // LRM §20.3: `$finish` yang sudah menyala pada tahap `initial` juga
        // harus menghentikan tahap clock. Tanpa penjagaan ini, loop `break`
        // di dalam tahap `initial` hanya keluar dari loop itu dan proses
        // sekuensial masih dievaluasi sekali lagi pada siklus pertama.
        if sv_codegen_rust::system_task_gen::has_finish(design) {
            out.push_str("    if !design.is_finished() {\n");
        }
        out.push_str("    // Clock simulation\n");
        out.push_str(&format!("    let clock_id = {};\n", clock));
        out.push_str("    for _cycle in 0..STEPS {\n");
        out.push_str("        design.eval_comb();\n");
        out.push_str("        design.commit_pending();\n");
        out.push_str("        design.eval_seq(clock_id);\n");
        out.push_str("        design.commit_pending();\n");
        // `$finish` menghentikan simulasi, jadi clock tidak terus berputar.
        if sv_codegen_rust::system_task_gen::has_finish(design) {
            out.push_str("        if design.is_finished() {\n");
            out.push_str("            break;\n");
            out.push_str("        }\n");
        }
        if sv_codegen_rust::system_task_gen::uses_monitor_flag(design) {
            out.push_str("        pantau_monitor!();\n");
        }
        // LRM §20.3: `$strobe` cetak di akhir timestep, setelah semua proses.
        if sv_codegen_rust::system_task_gen::has_strobe(design) {
            out.push_str("        design.run_strobe();\n");
        }
        if perlu_prev {
            out.push_str("        design.sample_edge();\n");
        }
        out.push_str("    }\n");
        if sv_codegen_rust::system_task_gen::has_finish(design) {
            out.push_str("    }\n");
        }
        out.push('\n');
    }

    write_output_prints(design, &mut out);
    out.push_str("}\n");
    out
}

/// Print nilai output di akhir simulasi.
fn write_output_prints(design: &Design, out: &mut String) {
    out.push_str("    // Output values\n");
    for port in &design.ports {
        if matches!(port.direction, PortDirection::Output | PortDirection::Inout) {
            // `to_hex_lebar` dipakai, bukan `to_hex`: yang latter tidak
            // membedakan "0" dari "belum diketahui", sehingga variabel yang
            // belum diinisialisasi tercetak `00` padahal LRM §4.3.1 memberi
            // nilai awal `x`.
            out.push_str(&format!(
                "    println!(\"{} = {{}}\", design.{}().to_hex_lebar({}));\n",
                port.name,
                port.name.to_lowercase(),
                port.data_type.width
            ));
        }
    }
}

/// Driver dengan capture VCD: stimulus counter per langkah + sampel tiap step.
fn generate_vcd_driver_named(
    design: &Design,
    steps: usize,
    vcd_path: &Path,
    fn_name: &str,
    module: &str,
) -> String {
    let struct_name = qualify(module, &sv_codegen_rust::to_struct_name(&design.name));
    let mut out = header_fungsi(&struct_name, fn_name, steps);

    // LRM §21.8: waktu simulasi untuk timestamp VCD, dalam satuan
    // `timeprecision` modul. Design tanpa `#delay`/`$time` tidak punya field
    // `time_now`; timestamp-nya tetap harus monoton (memakai konstanta 0
    // membuat seluruh waveform bertumpuk di t=0 dan tidak bisa dibaca).
    let waktu_dasar = if sv_codegen_rust::time_scan::has_time(design) {
        format!(
            "design.time_now().in_units({})",
            crate::vcd_timescale::precision_femtos(design)
        )
    } else {
        "i as u64".to_string()
    };
    // Nilai sebelum loop: belum ada `#delay` yang jalan, jadi waktunya nol.
    let waktu_dawal = "0".to_string();

    // LRM §21.8: header VCD memakai `timeprecision` modul top, bukan
    // nanosecond tetap — kalau tidak, pembaca VCD akan salah menafsirkan
    // nilai waktu.
    out.push_str(&format!(
        "    let mut trace = sv_trace::VcdWriter::new({:?});\n",
        crate::vcd_timescale::vcd_timescale(design)
    ));
    for var in &design.variables {
        let field = var.name.to_lowercase();
        out.push_str(&format!(
            "    let id_{} = trace.add_signal(\"{}\", {});\n",
            field, var.name, var.data_type.width
        ));
    }
    out.push_str("    trace.begin();\n");

    // Nilai awal setelah settle.
    out.push_str("\n    design.eval_comb();\n");
    out.push_str("    design.commit_pending();\n");
    // LRM §15.2: blok `initial` berjalan sekali pada waktu nol, sebelum
    // capture VCD sehingga stimulus testbench ikut terekam.
    let ada_initial = sv_codegen_rust::module_gen::has_initial(design);
    if ada_initial {
        out.push_str("    design.eval_initial(0);\n");
        out.push_str("    design.commit_pending();\n");
        out.push_str("    design.eval_comb();\n");
        out.push_str("    design.commit_pending();\n");
    }
    let bisa_dump = sv_codegen_rust::system_task_gen::has_dumpvars(design);
    if bisa_dump {
        // Status `$dumpvars` baru boleh dibaca setelah blok `initial` t=0 jalan.
        out.push_str("    let mut dumping = design.dump_requested();\n");
    } else {
        out.push_str("    let mut dumping = true;\n");
    }
    // Macro `$monitor` perlu dideklarasikan sebelum dipakai (macro_rules
    // bersifat tekstual), jadi ditaruh sebelum loop langkah.
    write_monitor_driver(
        sv_codegen_rust::system_task_gen::has_monitor(design),
        &mut out,
    );
    out.push_str("    if dumping {\n");
    out.push_str(&format!("    trace.initial({waktu_dawal}, &[\n"));
    for var in &design.variables {
        let field = var.name.to_lowercase();
        out.push_str(&format!(
            "            (id_{}, &design.{}().to_vcd_string()),\n",
            field, field
        ));
    }
    out.push_str("        ]);\n");
    out.push_str("    }\n");

    let clock = clock_signal_id(design);
    let clock_field = clock_var(design);

    // LRM §21.8: timestamp VCD dalam satuan `timeprecision` modul. Dulu
    // variabel `t` bertambah satu tiap langkah driver, jadi waveform menyatakan
    // nomor langkah, bukan waktu simulasi — pembaca VCD salah membaca setiap
    // edge.
    //
    let waktu = waktu_dasar.clone();
    let waktu_akhir = waktu.clone();

    out.push_str("\n    for i in 0..STEPS {\n");

    // Stimulus input: ramping counter agar terlihat transisi di VCD.
    for port in input_ports(design) {
        let field = port.name.to_lowercase();
        if let Some((cf, _)) = &clock_field {
            if cf == &field {
                continue;
            }
        }
        let m = stimulus_mod(port.data_type.width);
        out.push_str(&format!(
            "        design.set_{}(Bits::<{}>::from_u64((i as u64) % {}));\n",
            field, port.data_type.width, m
        ));
    }
    // Toggle clock bila ada proses sekuensial.
    if let Some((cf, cw)) = &clock_field {
        out.push_str(&format!(
            "        design.set_{}(Bits::<{}>::from_u64(((i as u64) % 2)));\n",
            cf, cw
        ));
    }

    out.push_str("        design.eval_comb();\n");
    out.push_str("        design.commit_pending();\n");
    // LRM §15.2: blok `initial` juga harus berjalan pada mode VCD. Tanpa ini
    // `time_now` tidak pernah bergerak dan seluruh timestamp VCD salah.
    if ada_initial {
        out.push_str("        design.eval_initial(i + 1);\n");
        out.push_str("        design.commit_pending();\n");
        out.push_str("        design.eval_comb();\n");
        out.push_str("        design.commit_pending();\n");
    }
    if bisa_dump {
        // LRM §23.2: `$dumpvars` boleh dipanggil setelah `#delay`. Statusnya
        // dibaca lagi setelah segmen `initial` berjalan; kalau tidak, blok
        // `$dumpvars` yang telat tidak pernah menghasilkan berkas dan pesannya
        // menyalahkan pengguna.
        out.push_str("        if !dumping && design.dump_requested() {\n");
        out.push_str("            dumping = true;\n");
        out.push_str(&format!("            trace.initial({waktu}, &["));
        for var in &design.variables {
            let field = var.name.to_lowercase();
            out.push_str(&format!(
                "                (id_{field}, &design.{field}().to_vcd_string()),\n"
            ));
        }
        out.push_str("            ]);\n");
        out.push_str("        }\n");
    }
    if let Some(id) = clock {
        out.push_str(&format!("        design.eval_seq({});\n", id));
        out.push_str("        design.commit_pending();\n");
    }
    // LRM §20.2/§20.3: `$monitor` dan `$strobe` juga harus jalan pada mode VCD.
    // Tanpa ini, design yang punya `$dumpvars` kehilangan seluruh cetakan
    // testbench — `$monitor` tidak pernah dievaluasi dan `$strobe` tidak
    // pernah dikuras.
    if sv_codegen_rust::system_task_gen::uses_monitor_flag(design) {
        out.push_str("        pantau_monitor!();\n");
    }
    if sv_codegen_rust::system_task_gen::has_strobe(design) {
        out.push_str("        design.run_strobe();\n");
    }
    // LRM §9.7: nilai sinyal yang diawasi disimpan untuk langkah berikutnya.
    if sv_codegen_rust::module_gen::perlu_edge_prev(design) {
        out.push_str("        design.sample_edge();\n");
    }
    if sv_codegen_rust::system_task_gen::has_finish(design) {
        // `$finish` menghentikan simulasi, jadi trace tidak perlu berlanjut.
        // Marker waktu akhir tetap ditulis supaya waveform menutup pada waktu
        // `$finish` dipanggil — `iverilog` menulis `#30` untuk `$finish` di
        // t=30, dan pembaca VCD memakai marker terakhir itu sebagai ujung trace.
        out.push_str("        let __selesai = design.is_finished();\n");
        out.push_str("        if __selesai {\n");
        out.push_str("            if dumping {\n");
        out.push_str(&format!(
            "                trace.advance({waktu_akhir}, &[]);\n"
        ));
        out.push_str("            }\n");
        out.push_str("            break;\n");
        out.push_str("        }\n");
    }

    out.push_str("        if dumping {\n");
    out.push_str(&format!("            trace.advance({waktu}, &[\n"));
    for var in &design.variables {
        let field = var.name.to_lowercase();
        out.push_str(&format!(
            "                (id_{}, &design.{}().to_vcd_string()),\n",
            field, field
        ));
    }
    out.push_str("            ]);\n");
    out.push_str("        }\n");
    out.push_str("    }\n\n");

    write_output_prints(design, &mut out);

    // LRM §23.2: tanpa `$dumpvars` yang dipanggil, tidak ada berkas yang ditulis.
    if bisa_dump {
        out.push_str("    // LRM §23.2: tanpa `$dumpvars` yang dipanggil, tidak ada berkas.\n");
        out.push_str("    if !dumping {\n");
        out.push_str(&format!(
            "        println!(\"$dumpvars tidak dipanggil: {} tidak ditulis\");\n",
            vcd_path.display()
        ));
        out.push_str("        return;\n");
        out.push_str("    }\n");
    }
    out.push_str("    trace.finish();\n");
    out.push_str(&format!(
        "    if let Err(e) = trace.write_to_file(\"{}\") {{\n",
        vcd_path.display()
    ));
    out.push_str("        eprintln!(\"gagal tulis VCD: {e}\");\n");
    out.push_str("        std::process::exit(1);\n");
    out.push_str("    }\n");
    out.push_str(&format!(
        "    println!(\"VCD tersimpan: {}\");\n",
        vcd_path.display()
    ));
    out.push_str("}\n");
    out
}

/// Potongan driver yang memancarkan `$monitor` saat ada sinyal berubah.
///
/// LRM §20.2: `$monitor` mencetak sekali saat didaftarkan, lalu mengulang
/// setiap kali nilai argumennya berubah pada langkah waktu berikutnya.
fn write_monitor_driver(has_monitor: bool, out: &mut String) {
    if !has_monitor {
        return;
    }
    out.push_str("    // LRM §20.2: $monitor cetak sekali, lalu ulang saat nilai berubah\n");
    out.push_str("    design.run_monitor();\n");
    out.push_str("    let mut __prev = design.snapshot();\n");
    out.push_str("    macro_rules! pantau_monitor {\n");
    out.push_str("        () => {\n");
    out.push_str("            let __now = design.snapshot();\n");
    out.push_str("            if __now != __prev {\n");
    out.push_str("                __prev = __now;\n");
    out.push_str("                design.run_monitor();\n");
    out.push_str("            }\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
}

fn input_ports(design: &Design) -> Vec<&PortInfo> {
    design
        .ports
        .iter()
        .filter(|p| p.direction == PortDirection::Input)
        .collect()
}

/// Id sinyal clock dari proses sekuensial pertama, bila ada.
fn clock_signal_id(design: &Design) -> Option<u32> {
    design
        .processes
        .iter()
        .find(|p| p.kind == ProcessKind::Sequential)
        .and_then(|p| p.sensitivity.first())
        .map(|s| s.signal)
}

/// Nama field & lebar variabel clock sekuensial, bila ada.
fn clock_var(design: &Design) -> Option<(String, u32)> {
    let id = clock_signal_id(design)?;
    let var = design.variables.iter().find(|v| v.signal_id == id)?;
    Some((var.name.to_lowercase(), var.data_type.width))
}

/// Modulus stimulus counter agar tidak meluap lebar sinyal.
fn stimulus_mod(width: u32) -> u64 {
    if width >= 63 {
        u64::MAX
    } else {
        1u64 << width
    }
}
