// Tanggung jawab: generate program driver simulasi (termasuk capture VCD).
use std::path::Path;
use sv_ir::design::{PortDirection, PortInfo};
use sv_ir::process::ProcessKind;
use sv_ir::Design;

/// Generate driver; bila `vcd` diisi, hasilkan driver dengan capture waveform.
pub fn generate_driver(design: &Design, steps: usize, vcd: Option<&Path>) -> String {
    match vcd {
        Some(path) => generate_vcd_driver(design, steps, path),
        None => generate_plain_driver(design, steps),
    }
}

fn header(steps: usize, struct_name: &str) -> String {
    format!(
        "// Generated by cargo-sv. Jangan edit manual.\n\
         const STEPS: usize = {};\n\n\
         fn main() {{\n    let mut design = {}::new();\n",
        steps, struct_name
    )
}

/// Driver tanpa VCD: set input nol, settle combinational, opsional clock.
fn generate_plain_driver(design: &Design, steps: usize) -> String {
    let struct_name = sv_codegen_rust::to_struct_name(&design.name);
    let mut out = header(steps, &struct_name);

    for port in input_ports(design) {
        out.push_str(&format!(
            "    design.set_{}(Bits::zero());\n",
            port.name.to_lowercase()
        ));
    }

    out.push_str("\n    // Settle combinational logic\n");
    out.push_str("    for _ in 0..STEPS {\n");
    out.push_str("        design.eval_comb();\n");
    out.push_str("        design.commit_pending();\n");
    out.push_str("    }\n\n");

    // LRM §15.2/§11.2: blok `initial` dipecah pada batas `#delay`. Setiap
    // segmen dijalankan pada langkah waktunya sendiri; di antara segmen,
    // logika combinational settle dan edge clock dievaluasi supaya proses
    // lain benar-benar melihat keadaan di waktu yang sama.
    // LRM §9.7: `edge_prev` disampel tiap langkah bila ada tunggu edge di
    // `initial` atau proses sekuensial dengan event control gabungan.
    let perlu_prev = sv_codegen_rust::module_gen::perlu_edge_prev(design);
    if sv_codegen_rust::module_gen::has_initial(design) {
        let clock_id = clock_signal_id(design);
        // LRM §9.7: `@(posedge clk)` hanya boleh lanjut kalau clock benar-benar
        // berubah, jadi clock ditoggle tiap langkah pada desain yang menunggu.
        let ada_tunggu = sv_codegen_rust::initial_step::total_tunggu(design) > 0;
        if ada_tunggu {
            if let Some((cf, cw)) = &clock_var(design) {
                out.push_str(&format!(
                    "    design.set_{}(Bits::<{}>::from_u64(0));\n",
                    cf, cw
                ));
            }
            out.push_str("    design.eval_initial(0);\n");
            out.push_str("    design.commit_pending();\n");
            out.push_str("    design.eval_comb();\n");
            out.push_str("    design.commit_pending();\n");
            if perlu_prev {
                out.push_str("    design.sample_edge();\n");
            }
        } else {
            out.push_str("    design.eval_initial(0);\n");
            out.push_str("    design.commit_pending();\n");
            out.push_str("    design.eval_comb();\n");
            out.push_str("    design.commit_pending();\n");
        }
        // Macro `$monitor` harus dideklarasikan sebelum dipakai (Rust macro
        //_rules bersifat tekstual), jadi diletakkan sebelum loop langkah.
        write_monitor_driver(
            sv_codegen_rust::system_task_gen::has_monitor(design),
            &mut out,
        );
        out.push_str(&format!(
            "    for __step in 1..{}::INITIAL_STEPS {{\n",
            struct_name
        ));
        if ada_tunggu {
            if let Some((cf, cw)) = &clock_var(design) {
                out.push_str(&format!(
                    "        design.set_{}(Bits::<{}>::from_u64((__step % 2) as u64));\n",
                    cf, cw
                ));
            }
        }
        out.push_str("        design.eval_initial(__step);\n");
        out.push_str("        design.commit_pending();\n");
        // LRM §20.3: `$finish` menghentikan simulasi. Bila segmen `initial`
        // yang baru saja jalan memanggil `$finish`, proses sekuensial tak
        // boleh lagi dievaluasi pada langkah yang sama.
        if sv_codegen_rust::system_task_gen::has_finish(design) {
            out.push_str("        if design.is_finished() {\n");
            out.push_str("            break;\n");
            out.push_str("        }\n");
        }
        out.push_str("        design.eval_comb();\n");
        out.push_str("        design.commit_pending();\n");
        match clock_id {
            Some(id) => {
                out.push_str(&format!("        design.eval_seq({});\n", id));
                out.push_str("        design.commit_pending();\n");
            }
            None => out.push_str("        // tanpa proses sekuensial pada design ini\n"),
        }
        if sv_codegen_rust::system_task_gen::has_finish(design) {
            out.push_str("        if design.is_finished() {\n");
            out.push_str("            break;\n");
            out.push_str("        }\n");
        }
        if sv_codegen_rust::system_task_gen::uses_monitor_flag(design) {
            out.push_str("        pantau_monitor!();\n");
        }
        // LRM §20.3: `$strobe` cetak di akhir timestep, setelah semua proses.
        if sv_codegen_rust::system_task_gen::has_strobe(design) {
            out.push_str("        design.run_strobe();\n");
        }
        // Nilai sinyal yang diawasi disimpan untuk langkah berikutnya.
        if perlu_prev {
            out.push_str("        design.sample_edge();\n");
        }
        out.push_str("    }\n\n");
    }

    if let Some(clock) = clock_signal_id(design) {
        // LRM §20.3: `$finish` yang sudah menyala pada tahap `initial` juga
        // harus menghentikan tahap clock. Tanpa penjagaan ini, loop `break`
        // di dalam tahap `initial` hanya keluar dari loop itu dan proses
        // sekuensial masih dievaluasi sekali lagi pada siklus pertama.
        if sv_codegen_rust::system_task_gen::has_finish(design) {
            out.push_str("    if !design.is_finished() {\n");
        }
        out.push_str("    // Clock simulation\n");
        out.push_str(&format!("    let clock_id = {};\n", clock));
        out.push_str("    for _cycle in 0..STEPS {\n");
        out.push_str("        design.eval_comb();\n");
        out.push_str("        design.commit_pending();\n");
        out.push_str("        design.eval_seq(clock_id);\n");
        out.push_str("        design.commit_pending();\n");
        // `$finish` menghentikan simulasi, jadi clock tidak terus berputar.
        if sv_codegen_rust::system_task_gen::has_finish(design) {
            out.push_str("        if design.is_finished() {\n");
            out.push_str("            break;\n");
            out.push_str("        }\n");
        }
        if sv_codegen_rust::system_task_gen::uses_monitor_flag(design) {
            out.push_str("        pantau_monitor!();\n");
        }
        // LRM §20.3: `$strobe` cetak di akhir timestep, setelah semua proses.
        if sv_codegen_rust::system_task_gen::has_strobe(design) {
            out.push_str("        design.run_strobe();\n");
        }
        if perlu_prev {
            out.push_str("        design.sample_edge();\n");
        }
        out.push_str("    }\n");
        if sv_codegen_rust::system_task_gen::has_finish(design) {
            out.push_str("    }\n");
        }
        out.push('\n');
    }

    write_output_prints(design, &mut out);
    out.push_str("}\n");
    out
}

/// Print nilai output di akhir simulasi.
fn write_output_prints(design: &Design, out: &mut String) {
    out.push_str("    // Output values\n");
    for port in &design.ports {
        if matches!(port.direction, PortDirection::Output | PortDirection::Inout) {
            // `to_hex_lebar` dipakai, bukan `to_hex`: yang latter tidak
            // membedakan "0" dari "belum diketahui", sehingga variabel yang
            // belum diinisialisasi tercetak `00` padahal LRM §4.3.1 memberi
            // nilai awal `x`.
            out.push_str(&format!(
                "    println!(\"{} = {{}}\", design.{}().to_hex_lebar({}));\n",
                port.name,
                port.name.to_lowercase(),
                port.data_type.width
            ));
        }
    }
}

/// Driver dengan capture VCD: stimulus counter per langkah + sampel tiap step.
fn generate_vcd_driver(design: &Design, steps: usize, vcd_path: &Path) -> String {
    let struct_name = sv_codegen_rust::to_struct_name(&design.name);
    let mut out = header(steps, &struct_name);

    // LRM §21.8: header VCD memakai `timeprecision` modul top, bukan
    // nanosecond tetap — kalau tidak, pembaca VCD akan salah menafsirkan
    // nilai waktu.
    out.push_str(&format!(
        "    let mut trace = sv_trace::VcdWriter::new({:?});\n",
        crate::vcd_timescale::vcd_timescale(design)
    ));
    for var in &design.variables {
        let field = var.name.to_lowercase();
        out.push_str(&format!(
            "    let id_{} = trace.add_signal(\"{}\", {});\n",
            field, var.name, var.data_type.width
        ));
    }
    out.push_str("    trace.begin();\n");

    // Nilai awal setelah settle.
    out.push_str("\n    design.eval_comb();\n");
    out.push_str("    design.commit_pending();\n");
    // LRM §15.2: blok `initial` berjalan sekali pada waktu nol, sebelum
    // capture VCD sehingga stimulus testbench ikut terekam.
    let ada_initial = sv_codegen_rust::module_gen::has_initial(design);
    if ada_initial {
        out.push_str("    design.eval_initial(0);\n");
        out.push_str("    design.commit_pending();\n");
        out.push_str("    design.eval_comb();\n");
        out.push_str("    design.commit_pending();\n");
    }
    let bisa_dump = sv_codegen_rust::system_task_gen::has_dumpvars(design);
    if bisa_dump {
        // Status `$dumpvars` baru boleh dibaca setelah blok `initial` t=0 jalan.
        out.push_str("    let mut dumping = design.dump_requested();\n");
    } else {
        out.push_str("    let mut dumping = true;\n");
    }
    out.push_str("    if dumping {\n");
    out.push_str("    trace.initial(&[\n");
    for var in &design.variables {
        let field = var.name.to_lowercase();
        out.push_str(&format!(
            "            (id_{}, &design.{}().to_vcd_string()),\n",
            field, field
        ));
    }
    out.push_str("        ]);\n");
    out.push_str("    }\n");

    let clock = clock_signal_id(design);
    let clock_field = clock_var(design);

    out.push_str("\n    let mut t: u64 = 0;\n");
    out.push_str("    for i in 0..STEPS {\n");

    // Stimulus input: ramping counter agar terlihat transisi di VCD.
    for port in input_ports(design) {
        let field = port.name.to_lowercase();
        if let Some((cf, _)) = &clock_field {
            if cf == &field {
                continue;
            }
        }
        let m = stimulus_mod(port.data_type.width);
        out.push_str(&format!(
            "        design.set_{}(Bits::<{}>::from_u64((i as u64) % {}));\n",
            field, port.data_type.width, m
        ));
    }
    // Toggle clock bila ada proses sekuensial.
    if let Some((cf, cw)) = &clock_field {
        out.push_str(&format!(
            "        design.set_{}(Bits::<{}>::from_u64(((i as u64) % 2)));\n",
            cf, cw
        ));
    }

    out.push_str("        design.eval_comb();\n");
    out.push_str("        design.commit_pending();\n");
    if let Some(id) = clock {
        out.push_str(&format!("        design.eval_seq({});\n", id));
        out.push_str("        design.commit_pending();\n");
    }
    // LRM §9.7: nilai sinyal yang diawasi disimpan untuk langkah berikutnya.
    if sv_codegen_rust::module_gen::perlu_edge_prev(design) {
        out.push_str("        design.sample_edge();\n");
    }
    if sv_codegen_rust::system_task_gen::has_finish(design) {
        // `$finish` menghentikan simulasi, jadi trace tidak perlu berlanjut.
        out.push_str("        if design.is_finished() {\n");
        out.push_str("            break;\n");
        out.push_str("        }\n");
    }

    out.push_str("        t += 1;\n");
    out.push_str("        if dumping {\n");
    out.push_str("            trace.advance(t, &[\n");
    for var in &design.variables {
        let field = var.name.to_lowercase();
        out.push_str(&format!(
            "                (id_{}, &design.{}().to_vcd_string()),\n",
            field, field
        ));
    }
    out.push_str("            ]);\n");
    out.push_str("        }\n");
    out.push_str("    }\n\n");

    write_output_prints(design, &mut out);

    // LRM §23.2: tanpa `$dumpvars` yang dipanggil, tidak ada berkas yang ditulis.
    if bisa_dump {
        out.push_str("    // LRM §23.2: tanpa `$dumpvars` yang dipanggil, tidak ada berkas.\n");
        out.push_str("    if !dumping {\n");
        out.push_str(&format!(
            "        println!(\"$dumpvars tidak dipanggil: {} tidak ditulis\");\n",
            vcd_path.display()
        ));
        out.push_str("        return;\n");
        out.push_str("    }\n");
    }
    out.push_str("    trace.finish();\n");
    out.push_str(&format!(
        "    if let Err(e) = trace.write_to_file(\"{}\") {{\n",
        vcd_path.display()
    ));
    out.push_str("        eprintln!(\"gagal tulis VCD: {e}\");\n");
    out.push_str("        std::process::exit(1);\n");
    out.push_str("    }\n");
    out.push_str(&format!(
        "    println!(\"VCD tersimpan: {}\");\n",
        vcd_path.display()
    ));
    out.push_str("}\n");
    out
}

/// Potongan driver yang memancarkan `$monitor` saat ada sinyal berubah.
///
/// LRM §20.2: `$monitor` mencetak sekali saat didaftarkan, lalu mengulang
/// setiap kali nilai argumennya berubah pada langkah waktu berikutnya.
fn write_monitor_driver(has_monitor: bool, out: &mut String) {
    if !has_monitor {
        return;
    }
    out.push_str("    // LRM §20.2: $monitor cetak sekali, lalu ulang saat nilai berubah\n");
    out.push_str("    design.run_monitor();\n");
    out.push_str("    let mut __prev = design.snapshot();\n");
    out.push_str("    macro_rules! pantau_monitor {\n");
    out.push_str("        () => {\n");
    out.push_str("            let __now = design.snapshot();\n");
    out.push_str("            if __now != __prev {\n");
    out.push_str("                __prev = __now;\n");
    out.push_str("                design.run_monitor();\n");
    out.push_str("            }\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
}

fn input_ports(design: &Design) -> Vec<&PortInfo> {
    design
        .ports
        .iter()
        .filter(|p| p.direction == PortDirection::Input)
        .collect()
}

/// Id sinyal clock dari proses sekuensial pertama, bila ada.
fn clock_signal_id(design: &Design) -> Option<u32> {
    design
        .processes
        .iter()
        .find(|p| p.kind == ProcessKind::Sequential)
        .and_then(|p| p.sensitivity.first())
        .map(|s| s.signal)
}

/// Nama field & lebar variabel clock sekuensial, bila ada.
fn clock_var(design: &Design) -> Option<(String, u32)> {
    let id = clock_signal_id(design)?;
    let var = design.variables.iter().find(|v| v.signal_id == id)?;
    Some((var.name.to_lowercase(), var.data_type.width))
}

/// Modulus stimulus counter agar tidak meluap lebar sinyal.
fn stimulus_mod(width: u32) -> u64 {
    if width >= 63 {
        u64::MAX
    } else {
        1u64 << width
    }
}
