// Tanggung jawab: manage direktori keluaran target/sv dan proyek simulasi.
use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

pub struct Workspace {
    target_sv: PathBuf,
    sim_dir: PathBuf,
}

impl Workspace {
    pub fn detect() -> Result<Self, String> {
        let cwd = env::current_dir().map_err(|e| e.to_string())?;
        let target_sv = cwd.join("target").join("sv");
        let sim_dir = env::temp_dir().join("sv-sim");
        Ok(Self { target_sv, sim_dir })
    }

    pub fn generated_dir(&self) -> PathBuf {
        self.target_sv.join("generated")
    }

    pub fn sim_project_dir(&self) -> PathBuf {
        self.sim_dir.clone()
    }

    pub fn ensure_dirs(&self) -> Result<(), String> {
        fs::create_dir_all(self.generated_dir()).map_err(|e| e.to_string())?;
        fs::create_dir_all(&self.sim_dir).map_err(|e| e.to_string())?;
        Ok(())
    }

    pub fn write_generated(&self, design_name: &str, rust_code: &str) -> Result<PathBuf, String> {
        self.ensure_dirs()?;
        let mod_name = sv_codegen_rust::to_module_name(design_name);
        let path = self.generated_dir().join(mod_name).with_extension("rs");
        fs::write(&path, rust_code).map_err(|e| e.to_string())?;
        Ok(path)
    }

    /// Tulis proyek simulasi: satu `mod` per design lalu driver.
    ///
    /// Tiap design dibungkus module Rust sendiri karena beberapa modul root
    /// bisa sama-sama mendeklarasikan `MAX_WIDTH` dan `use` yang sama di
    /// lingkup atas — digabung apa adanya, kode hasil generate gagal dengan
    /// `the name MAX_WIDTH is defined multiple times`.
    pub fn write_sim_project(
        &self,
        designs: &[(&str, &str)],
        driver_code: &str,
        pakai_vcd: bool,
    ) -> Result<PathBuf, String> {
        // Buat proyek simulasi di temp dir dengan dependensi path ke sv-runtime.
        let sim_dir = self.sim_dir.clone();
        let src_dir = sim_dir.join("src");
        fs::create_dir_all(&src_dir).map_err(|e| e.to_string())?;

        // Cari path absolut crate sv-runtime dan sv-trace dari workspace root.
        let cwd = env::current_dir().map_err(|e| e.to_string())?;
        let runtime_path = cwd.join("crates").join("sv-runtime");

        // Cargo.toml memakai path dependency agar tidak duplikasi runtime.
        // `sv-trace` hanya ditulis bila driver merekam VCD supaya dependensi
        // tidak pernah terdeteksi tidak terpakai.
        let mut cargo_toml = format!(
            "[package]\nname = \"sv-sim\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n\
             [dependencies]\n\
             sv-runtime = {{ path = \"{}\" }}\n",
            runtime_path.display()
        );
        if pakai_vcd {
            let trace_path = cwd.join("crates").join("sv-trace");
            cargo_toml.push_str(&format!(
                "sv-trace = {{ path = \"{}\" }}\n",
                trace_path.display()
            ));
        }
        fs::write(sim_dir.join("Cargo.toml"), cargo_toml).map_err(|e| e.to_string())?;

        // src/main.rs gabung generated code dan driver.
        // `unused_parens`: grouping pada ekspresi ditulis oleh codegen untuk
        // keamanan presedensi; sebagian besar tidak perlu di sisi Rust.
        let mut main_content = String::from(
            // `unused_parens`: grouping ditulis codegen untuk keamanan
            // presedensi. `unused_imports`: `Bits` dipakai hanya desain
            // tertentu, dan `non_snake_case`: nama parameter driver mengikuti
            // gaya SV. Ketiganya unavoidable di kode hasil generate, dan
            // LRM_COMPLIANCE.md mengklaim proyek sim hasil generate 0 warning.
            "// Generated by cargo-sv. Jangan edit manual.\n\
             #![allow(unused_parens, unused_imports, non_snake_case)]\n\n",
        );
        for (module, rust_code) in designs {
            main_content.push_str(&format!("mod {module} {{\n"));
            main_content.push_str(rust_code);
            main_content.push_str("\n}\n\n");
        }
        // Driver berada di lingkup luar module design, jadi ia butuh
        // `Bits` sendiri — tanpa ini kode simulasi gagal dengan
        // `cannot find type Bits in this scope`. Path absolut (`::`) supaya
        // modul design yang namanya `sv_runtime` tidak memblokir crate asli.
        main_content.push_str("use ::sv_runtime::Bits;\n\n");
        main_content.push_str(driver_code);

        fs::write(src_dir.join("main.rs"), main_content).map_err(|e| e.to_string())?;

        Ok(sim_dir.join("Cargo.toml"))
    }

    pub fn build(&self, release: bool) -> Result<(), String> {
        let mut cmd = Command::new("cargo");
        cmd.arg("build");
        if release {
            cmd.arg("--release");
        }
        cmd.current_dir(&self.sim_dir);
        let status = cmd
            .status()
            .map_err(|e| format!("gagal jalankan cargo: {}", e))?;
        if !status.success() {
            return Err("cargo build gagal".to_string());
        }
        Ok(())
    }

    pub fn run(&self, release: bool) -> Result<(), String> {
        let mut cmd = Command::new("cargo");
        cmd.arg("run");
        if release {
            cmd.arg("--release");
        }
        cmd.current_dir(&self.sim_dir);
        let status = cmd
            .status()
            .map_err(|e| format!("gagal jalankan cargo: {}", e))?;
        if !status.success() {
            return Err("cargo run gagal".to_string());
        }
        Ok(())
    }

    pub fn clean(&self) -> Result<(), String> {
        if self.target_sv.exists() {
            fs::remove_dir_all(&self.target_sv).map_err(|e| e.to_string())?;
        }
        if self.sim_dir.exists() {
            fs::remove_dir_all(&self.sim_dir).map_err(|e| e.to_string())?;
        }
        // Also clean workspace temp dirs
        let ws_root = env::temp_dir().join("sv-workspace");
        if ws_root.exists() {
            fs::remove_dir_all(&ws_root).map_err(|e| e.to_string())?;
        }
        let gen_temp = env::temp_dir().join("sv-generated-temp");
        if gen_temp.exists() {
            fs::remove_dir_all(&gen_temp).map_err(|e| e.to_string())?;
        }
        Ok(())
    }
}
